## Define a 'Service' To Expose MySQL to Other Services
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3307
      targetPort: 3306
  selector:
    app: mysql
    tier: database